	
name: Deploy to GitHub Pages
name: Deploy to GitHub Pages
on:
on:
  push:
  push:
    branches:
    branches:
      - main
      - main
jobs:
jobs:
  build-and-deploy:
  build-and-deploy:
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    steps:
    - name: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      uses: actions/checkout@v3
    - name: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      uses: actions/setup-node@v3
      with:
      with:
        node-version: '20'
        node-version: '20'
    - name: Install dependencies
    - name: Install dependencies
      run: npm ci
      run: npm ci
    - name: Build
    - name: Build
      run: npm run build
      run: npm run build
    - name: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      uses: peaceiris/actions-gh-pages@v3
      with:
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_dir: ./dist
Agora, vamos atualizar o arquivo vite.config.js para incluir a configuração base:
<lov-write file_path="vite.config.js">
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: '/healthwise-boost/', // Substitua 'healthwise-boost' pelo nome do seu repositório
})
